import Header from "@/components/header";
import Dropdown from "@/components/dropdown";
import { ToastContainer, toast } from "react-toastify";

export const metadata = {
  title: "CRM - Loyalty Card",
  description: "Generated by create next app",
};

export default function GiftCardLayout({ children }) {
  return (
    <section>
      <div className="sticky top-0 z-50">
        <Header />
        <Dropdown />
      </div>
      {children}
    </section>
  );
}
